### ISSUE TITLE
Move from 'monad-logger' to 'co-log'

### ISSUE THREAD

**Issue by chshersh** [Holmusk/three-layer#10]

**Comment by ChShersh** [comment]
For now I see that it's not that convenient to move to `katip` without introducing lenses to `AppEnv` first. `katip` library requires to have some instances for our `App` monad and those instances require changing value of `AppEnv`. If we have something like that:

```haskell
data LoggerConfig = LoggerConfig 
  { lfNamespace :: Namespace
  , lfContext   :: LogContexts
  , lfLogEnv    :: LogEnv
  }
```

and put this to `AppEnv` we need to write instances like that:

```haskell
instance Katip App where
  getLogEnv = asks lfLogEnv
  localLogEnv f (App m) = App (local (\s -> s { msLogEnv = f (lfLogEnv s)}) m)


instance KatipContext App where
  getKatipContext = asks lfContext
  localKatipContext f (App m) = App (local (\s -> s { lfContext = f (lfContext s)}) m)
  getKatipNamespace = asks lfNamespace
  localKatipNamespace f (App m) = App (local (\s -> s { lfNamespace = f (lfNamespace s)}) m)
```

but only uglier. This instance works only if we store fields of `LoggerConfig` directly in `AppEnv` which seems a little awkward to me. And if you add one extra nested layer to those instances above, code will be much uglier...  Though this might be the low cost.

**Comment by ChShersh** [comment]
Okay, there's one difficulty with migration to `katip`. I want to use `NoLoggingT` in mock tests but library doesn't export `runNoLoggingT` unwrapper 😞 I've opened issue for this:

* https://github.com/Soostone/katip/issues/89

**Comment by ChShersh** [comment]
PR with fixes was merged to `katip` repository. But new version is not released. I will reopen this issue just as a reminder to not forget to update repo.
