### ISSUE TITLE
[Question] How to remove 'hoistServer'

### ISSUE THREAD

**Issue by Cmdv** [Holmusk/three-layer#81]
I've been trying to make a simpler version of three-layers, which doesn't have logging but I'm not able to find out what I need to put in place of `hoistServer` from bellow?

https://github.com/Holmusk/three-layer/blob/1b58ec102f206681b66a584ca4a7d18f2eb4ef81/src/Lib/Server.hs#L16-L25

This is what I have so far but also unsure if I should be passing my `AppEnv` through to my `httpServer`:

```Haskell
type AppApi = ToApi HttpSite

-- | These are the routes to the http app
data HttpSite route = HttpSite
    { -- | Post Hello
      helloRoute :: route
        :- "hello"
        :> Post '[JSON] HelloRes
    } deriving (Generic)

newtype HelloRes = HelloRes { msg :: String }
  deriving Generic

instance ToJSON HelloRes

httpServer :: HttpSite AppServer
httpServer = HttpSite
    { helloRoute = helloHandler
    }

-- | update the request count by one and return
helloHandler :: ( MonadStats m ) => m HelloRes
helloHandler = do
    reqCount <- getStats
    let newReqCount = (reqCount + 1)
    putStats newReqCount
    pure $ HelloRes (show newReqCount)

httpApp :: AppEnv -> Application
httpApp env = serve
    (Proxy @AppApi)
    httpServer -- ?? should I pass the env
```
right now I get the error:
```
Couldn't match type ‘Handler HelloRes’ with ‘HttpSite AppServer’
Expected type: Server ("hello" :> Post '[JSON] HelloRes)
```

I've been trying to look through the docs for servant but can't find anything that helps 😸

**Comment by jhrcek** [comment]
Do I understand it right that you just want to remove ability to log (like debugging / informational / warning) messages?
That has nothing to do with hoisting the server. If I were to remove that I would just remove the Log action from the environment https://github.com/Holmusk/three-layer/blob/1b58ec102f206681b66a584ca4a7d18f2eb4ef81/src/Lib/App/Env.hs#L34
And the follow through by removing all the remaining pieces causing the compiler errors (e.g remove the log effect functions etc.)

The purpose of hoistServer is to convert  handlers implemented in the [App](https://github.com/Holmusk/three-layer/blob/master/src/Lib/App/Monad.hs#L19-L22) monad (which servant doesn't know how to use) into handlers within servant's [Handler](https://hackage.haskell.org/package/servant-server-0.18/docs/Servant-Server.html#t:Handler) monad.

In the case of this repo `App` is just a newtype wrapper of `ReaderT` monad so `hoistServer` achieves the conversion to Handler monad by using  [runAppAsHandler](https://github.com/Holmusk/three-layer/blob/9638ba0709b023a3d20e8a72fcd44b2ccc720359/src/Lib/Effects/Log.hs#L29) function which "runs" the ReadeT by providing environment to it and handling the errors etc.

If you should remove the `ReaderT` from `App` abstraction you might not need three-layer at all. But then (without `hoistServer`) you would have to implement your handlers directly in `Handler` monad. You can find more info in the official servant documentation: https://docs.servant.dev/en/stable/tutorial/Server.html?highlight=hoistServer#welcome-hoistserver

**Comment by Cmdv** [comment]
@jhrcek thanks for the reply, think I'm going to have to go through the Servant docs from scratch 😅 

Because what I'm actually do is share the `appMonad` between a websocket server and the normal api server.

```Haskell
runServer :: AppEnv -> IO ()
runServer env = do
    run 8080 $
      websocketsOr
        defaultConnectionOptions
        (wsApp env)
        (httpApp env)
```
https://github.com/Cmdv/servant-websocket-example/blob/5efa12fb4594277788a4301195002732f5769fc8/src/Lib.hs#L24-L30

so when I go into `httpApp` I'm unsure what I would replace `runAppAsHandler` with as I plan on sharing `AppMonad` between both `wsApp` + `httpApp`.

```Haskell
server :: AppEnv -> Server Api
server env = hoistServer
    (Proxy @Api)
    (pure _)
    (toServant httpServer)
```
https://github.com/Cmdv/servant-websocket-example/blob/916dde8381c47fe5fead996e37246db03d9df645/src/Lib/HttpServer/Server.hs#L45-L49

But I think to work that out I need to go more in-depth with Servant and Wai as I don't want to be asking too many non repo related questions.

**Comment by Cmdv** [comment]
ahh ok I totally had things the wrong way around I thought that `Handler` was something different.

What I was actually looking for was bellow, using `runAppAsHandler`:

```Haskell
runAppAsHandler :: AppEnv -> App a -> Handler a
runAppAsHandler env app = do
  liftIO $ runApp env app

runApp :: AppEnv -> App a -> IO a
runApp env = flip runReaderT env . unApp
```

Thank you for the help 😄 now to work out how I can share state across both websockets and my api server  👍 

I'll close this issue too
